### PR TITLE
virus_scan_s3_bucket: don't try to be so clever in counting

### PR DESCRIPTION
**Pull request by risicle**
https://trello.com/c/aWnL8fAa/192-antivirus-create-catch-up-bulk-scan-script

@lfdebrux alerted me that integer increment in python is indeed *not* atomic. So instead don't try to be such a smartass in the file counting and instead pass the counts in the map function results and accumulate in the loop...

### CODE REVIEW

**Comment by risicle** [comment]
Think we might have the first case of "tests work for me, but..."

**Comment by risicle** [comment]
No, I was just looking through the meaning of the word **non**local

**Comment by lfdebrux** [comment]
While I appreciate that you have already changed the counting logic a lot, I think some of the legacy of the original form is now obscuring the intent.

I think it would be easier to read if the `handle_version` function were to return a status string such as `'pass'`, '`already_tagged`', etc, and then the counting could take place purely outside of the `handle_version` function.

Let me know if you disagree.

**Comment by risicle** [comment]
That's also a possibility, was just trying to avoid having a the sort of function that can have unknown or unexpected responses. Also that forces the function to classify a result as one category when the caller might want to count different properties of the response. Ultimately it still bears the mark of the fact that it's really just a broken-out loop body, but I'm ok with that - it's just a little script.

**Comment by risicle** [comment]
Right - I think this method just trades one set of future difficulties or for an equal alternative and isn't any more readable. But I really don't think it makes much difference either way.

**Pull request merged**
